apiVersion: v1
kind: Service
metadata:
  name: feedreader
spec:
  selector:
    app: feedreader
    app.kubernetes.io/name: feedreader
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedreader
  labels:
    app: feedreader
    app.kubernetes.io/name: feedreader
spec:
  selector:
    matchLabels:
      app: feedreader
  template:
    metadata:
      labels:
        app: feedreader
        app.kubernetes.io/name: feedreader
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: app
        image: ghcr.io/kasuboski/feedreader:main
        env:
        - name: FEED_DB_PATH
          value: "/feedreader/db/feeds.db"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3030
        volumeMounts:
        - name: db
          mountPath: "/feedreader/db"
      volumes:
      - name: db
        emptyDir: {}

