services:
  feedreader:
    image: ghcr.io/kasuboski/feedreader:main
    ports:
      - "4000:3000"
    environment:
      DATABASE_PATH: "/data/feedreader.db"
    volumes:
      - feedreader-data:/data
    restart: unless-stopped

volumes:
  feedreader-data:
