name: ci

on:
  push:
    paths:
      - "src/**"
      - "templates/**"
      - "Cargo.*"
      - "Earthfile"
      - "**/*.nix"
      - ".github/workflows/ci.yaml"
  workflow_dispatch: {}

jobs:
  nix:
    strategy:
      matrix:
        target: ["arm64", "amd64"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "CI_SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
        with:
          github-token: ${{ github.token }}
      - uses: cachix/cachix-action@v15
        with:
          name: kasuboski-feedreader
          extraPullNames: nix-community
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Feedreader
        env:
          EARTHLY_ORG: kasuboski
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
          EARTHLY_SATELLITE: ${{ matrix.target }}
        run: |
          nix develop --command just image
          nix develop --command just list-images

  multi-push:
    runs-on: ubuntu-latest
    needs: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "CI_SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v2
        with:
          github-token: ${{ github.token }}
      - uses: cachix/cachix-action@v15
        with:
          name: kasuboski-feedreader
          extraPullNames: nix-community
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Combine and Push images
        run: |
          nix develop --command just multiarch-push
